language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install
script:
    - xcodebuild test -workspace EasyMappingKit.xcworkspace -scheme EasyMappingKit -sdk iphonesimulator
