os: osx
osx_image: xcode11.2

language: objective-c
cache: cocoapods

before_install:
    - gem install xcpretty -N --no-document
    - xcrun simctl delete 38C891AB-EC79-43E4-9311-6FDEB12DCF11 || true # https://github.com/travis-ci/travis-ci/issues/7580
    - pod install

env:
  global:
  - WORKSPACE=FastEasyMapping.xcworkspace
  - RUN_TESTS="YES"
  - IOS_SCHEME="FastEasyMapping iOS"
  - MACOS_SCHEME="FastEasyMapping macOS"
  - TVOS_SCHEME="FastEasyMapping tvOS"
  - WATCHOS_SCHEME="FastEasyMapping watchOS"

  - IOS_SDK=iphonesimulator13.2
  - MACOS_SDK=macosx10.15
  - TVOS_SDK=appletvsimulator13.2
  - WATCHOS_SDK=watchsimulator6.1

  matrix:
      - SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" DESTINATION="OS=11.4,name=iPhone 6"
      - SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" DESTINATION="OS=12.1,name=iPhone SE"
      - SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" DESTINATION="OS=13.2.2,name=iPhone 8"

      - SCHEME="$MACOS_SCHEME" SDK="$MACOS_SDK" DESTINATION="arch=x86_64"

      - SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" DESTINATION="OS=12.1,name=Apple TV 4K (at 1080p)" RUN_TESTS="NO"
      - SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" DESTINATION="OS=13.2,name=Apple TV 4K (at 1080p)" RUN_TESTS="NO"

      - SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" DESTINATION="OS=5.1,name=Apple Watch Series 2 - 38mm" RUN_TESTS="NO"
      - SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" DESTINATION="OS=6.1,name=Apple Watch Series 5 - 44mm" RUN_TESTS="NO"

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - instruments -s devices

    # Build Framework in Debug and Run Tests if specified
    - |
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild build-for-testing -configuration Debug -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
        xcodebuild test-without-building -configuration Debug -enableCodeCoverage YES -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
      else
        xcodebuild build -configuration Debug -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
      fi;

    # Build Framework in Release and Run Tests if specified
    - |
      if [ $RUN_TESTS == "YES" ]; then
        xcodebuild build-for-testing -configuration Release -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
        xcodebuild test-without-building -configuration Release -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
      else
        xcodebuild build -configuration Release -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty
      fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
